import { ReactNode } from "react"
import { Nunito_Sans as NunitoSans } from "next/font/google"

import "./globals.css"

const nunito = NunitoSans({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${nunito.className} bg-gray-800 text-gray-100`}>
        {children}
      </body>
    </html>
  )
}
